import {
  isAiConfigured,
  requireAiConfig,
  type AiProviderConfig,
} from '@/config/env';

import { AnthropicProvider } from './provider/anthropic-provider';
import { AiProviderError } from './provider/errors';
import { FakeProvider } from './provider/fake-provider';
import type { AiProvider } from './provider/types';

/**
 * Provider construction from validated configuration (Stage 6).
 *
 * This is the single place that maps a config to a concrete {@link AiProvider}.
 * Keeping it isolated means the enrichment service and admin trigger depend only
 * on the interface, and adding a provider is a change here plus a new adapter —
 * nothing else. Misconfiguration surfaces as a non-retryable AiProviderError so
 * the caller records a failure and leaves everything else intact.
 */
/**
 * Canned, schema-valid output for the CONFIGURED fake provider (local/smoke use).
 * Tests never see this — they construct their own {@link FakeProvider} with an
 * explicit script. It exists only so `AI_PROVIDER=fake` yields a realistic
 * SUCCEEDED enrichment when an editor clicks "Run AI enrichment" locally.
 */
const CANNED_FAKE_OUTPUT = {
  relevance: 'MAYBE_RELEVANT',
  relevanceReason:
    'Fake provider output — replace AI_PROVIDER with a live provider for real analysis.',
  summary: 'Placeholder summary generated by the fake AI provider.',
  whyItMatters:
    'This is deterministic fake output used to exercise the enrichment pipeline.',
  suggestedTopics: [],
  suggestedEntities: [],
  confidence: 0.5,
};

export function buildProvider(config: AiProviderConfig): AiProvider {
  switch (config.provider) {
    case 'fake':
      return new FakeProvider({
        model: config.model,
        respondWith: CANNED_FAKE_OUTPUT,
      });
    case 'anthropic':
      if (!config.apiKey) {
        throw new AiProviderError(
          'MISCONFIGURED',
          'Anthropic provider requires an API key.',
        );
      }
      return new AnthropicProvider({
        apiKey: config.apiKey,
        model: config.model,
        baseUrl: config.baseUrl,
      });
    default: {
      // Exhaustiveness guard: a new provider enum value must be handled here.
      const never: never = config.provider;
      throw new AiProviderError(
        'MISCONFIGURED',
        `Unsupported AI provider: ${String(never)}`,
      );
    }
  }
}

/**
 * Resolve the configured provider from the environment, or throw a clear,
 * non-retryable error when AI is not configured. Enrichment code calls this; no
 * other subsystem does, so AI stays optional.
 */
export function resolveConfiguredProvider(): AiProvider {
  let config: AiProviderConfig;
  try {
    config = requireAiConfig();
  } catch (error) {
    throw new AiProviderError(
      'MISCONFIGURED',
      error instanceof Error ? error.message : 'AI provider is not configured.',
    );
  }
  return buildProvider(config);
}

/** Whether AI enrichment is configured for this deployment (never throws). */
export function aiConfigured(): boolean {
  return isAiConfigured();
}
